language: cpp

compiler:
  - gcc
  - clang

sudo: required

before_install:
  - echo $LANG
  - echo $LC_ALL
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version
  - sudo apt-get update

before_script:
  - cmake Development/Src/CMakeLists.txt
script:
  - cmake --build
  
branches:
  only:
    - develop_unstable

os:
  - linux
  - osx

osx_image: xcode61